spring.application.name=sistema-agendamento
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_agendamento
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true